version: "3.9"

services:
  node-server:
    container_name: sunnyvale_demo
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/user/src/app
    ports:
      - 3000:3000
    env_file:
      - .env
